/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log   :   This file is generated by Anlogic IP Generator.
 ** File   :   /home/forth32/dvk-fpga/board/tang/ip-components/tang_vm1_vcram.v
 ** Date   :   2021 03 18
 ** TD version   :   4.6.18154
\************************************************************/

`timescale 1ns / 1ps

module tang_vm1_vcram ( 
   doa, dia, addra, clka, wea,
   dob, dib, addrb, clkb, web
);

   output [15:0] doa;
   output [15:0] dob;


   input  [15:0] dia;
   input  [15:0] dib;
   input  [5:0] addra;
   input  [5:0] addrb;
   input  [1:0] wea;
   input  [1:0] web;
   input  clka;
   input  clkb;




   EG_LOGIC_BRAM #( .DATA_WIDTH_A(16),
            .DATA_WIDTH_B(16),
            .ADDR_WIDTH_A(6),
            .ADDR_WIDTH_B(6),
            .DATA_DEPTH_A(64),
            .DATA_DEPTH_B(64),
            .BYTE_ENABLE(8),
            .BYTE_A(2),
            .BYTE_B(2),
            .MODE("DP"),
            .REGMODE_A("NOREG"),
            .REGMODE_B("NOREG"),
            .WRITEMODE_A("NORMAL"),
            .WRITEMODE_B("NORMAL"),
            .RESETMODE("SYNC"),
            .IMPLEMENT("9K"),
            .INIT_FILE("../ram/vm1_vcram.mif"),
            .FILL_ALL("NONE"))
         inst(
            .dia(dia),
            .dib(dib),
            .addra(addra),
            .addrb(addrb),
            .cea(1'b1),
            .ceb(1'b1),
            .ocea(1'b0),
            .oceb(1'b0),
            .clka(clka),
            .clkb(clkb),
            .wea(1'b0),
            .bea(wea),
            .web(1'b0),
            .beb(web),
            .rsta(1'b0),
            .rstb(1'b0),
            .doa(doa),
            .dob(dob));


endmodule