/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log   :   This file is generated by Anlogic IP Generator.
 ** File   :   /home/forth32/dvk-fpga/board/tang/ip-components/tang_rom000.v
 ** Date   :   2021 03 18
 ** TD version   :   4.6.18154
\************************************************************/

`timescale 1ns / 1ps

module tang_rom000 ( doa, addra, clka, rsta );

   output [15:0] doa;

   input  [11:0] addra;
   input  clka;
   input  rsta;




   EG_LOGIC_BRAM #( .DATA_WIDTH_A(16),
            .ADDR_WIDTH_A(12),
            .DATA_DEPTH_A(4096),
            .DATA_WIDTH_B(16),
            .ADDR_WIDTH_B(12),
            .DATA_DEPTH_B(4096),
            .MODE("SP"),
            .REGMODE_A("NOREG"),
            .RESETMODE("SYNC"),
            .IMPLEMENT("9K"),
            .DEBUGGABLE("NO"),
            .PACKABLE("NO"),
            .INIT_FILE("../../../rom/000.mif"),
            .FILL_ALL("NONE"))
         inst(
            .dia({16{1'b0}}),
            .dib({16{1'b0}}),
            .addra(addra),
            .addrb({12{1'b0}}),
            .cea(1'b1),
            .ceb(1'b0),
            .ocea(1'b0),
            .oceb(1'b0),
            .clka(clka),
            .clkb(1'b0),
            .wea(1'b0),
            .web(1'b0),
            .bea(1'b0),
            .beb(1'b0),
            .rsta(rsta),
            .rstb(1'b0),
            .doa(doa),
            .dob());


endmodule