/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log   :   This file is generated by Anlogic IP Generator.
 ** File   :   /home/forth32/dvk-fpga/board/tang/ip-components/tang_fontrom.v
 ** Date   :   2021 03 17
 ** TD version   :   4.6.18154
\************************************************************/

`timescale 1ns / 1ps

module tang_fontrom ( doa, addra, clka, rsta );

   output [0:0] doa;

   input  [14:0] addra;
   input  clka;
   input  rsta;




   EG_LOGIC_BRAM #( .DATA_WIDTH_A(1),
            .ADDR_WIDTH_A(15),
            .DATA_DEPTH_A(32768),
            .DATA_WIDTH_B(1),
            .ADDR_WIDTH_B(15),
            .DATA_DEPTH_B(32768),
            .MODE("SP"),
            .REGMODE_A("NOREG"),
            .RESETMODE("SYNC"),
            .IMPLEMENT("9K"),
            .DEBUGGABLE("NO"),
            .PACKABLE("NO"),
            .INIT_FILE(`fontrom_file),
            .FILL_ALL("NONE"))
         inst(
            .dia({1{1'b0}}),
            .dib({1{1'b0}}),
            .addra(addra),
            .addrb({15{1'b0}}),
            .cea(1'b1),
            .ceb(1'b0),
            .ocea(1'b0),
            .oceb(1'b0),
            .clka(clka),
            .clkb(1'b0),
            .wea(1'b0),
            .web(1'b0),
            .bea(1'b0),
            .beb(1'b0),
            .rsta(rsta),
            .rstb(1'b0),
            .doa(doa),
            .dob());


endmodule
