/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log   :   This file is generated by Anlogic IP Generator.
 ** File   :   /home/forth32/dvk-fpga/board/tang/ip-components/tang_vtmem.v
 ** Date   :   2021 03 17
 ** TD version   :   4.6.18154
\************************************************************/

`timescale 1ns / 1ps

module tang_vtmem ( doa, dia, addra, clka, wea );

   output [15:0] doa;

   input  [15:0] dia;
   input  [10:0] addra;
   input  [1:0] wea;
   input  clka;



   EG_LOGIC_BRAM #( .DATA_WIDTH_A(16),
            .ADDR_WIDTH_A(11),
            .DATA_DEPTH_A(2048),
            .DATA_WIDTH_B(16),
            .ADDR_WIDTH_B(11),
            .DATA_DEPTH_B(2048),
            .BYTE_ENABLE(8),
            .BYTE_A(2),
            .BYTE_B(2),
            .MODE("SP"),
            .REGMODE_A("NOREG"),
            .WRITEMODE_A("NORMAL"),
            .RESETMODE("SYNC"),
            .IMPLEMENT("9K"),
            .DEBUGGABLE("NO"),
            .PACKABLE("NO"),
            .INIT_FILE("../../../ksm-firmware/ksm-firmware.mif"),
            .FILL_ALL("NONE"))
         inst(
            .dia(dia),
            .dib({16{1'b0}}),
            .addra(addra),
            .addrb({11{1'b0}}),
            .cea(1'b1),
            .ceb(1'b0),
            .ocea(1'b0),
            .oceb(1'b0),
            .clka(clka),
            .clkb(1'b0),
            .wea(1'b0),
            .bea(wea),
            .web(1'b0),
            .rsta(1'b0),
            .rstb(1'b0),
            .doa(doa),
            .dob());


endmodule