# This file is generated by Anlogic Timing Wizard. 22 03 2021

#Created Clock
create_clock -name clk24 -period 41.667 -waveform { 0.000 20.834 } [get_ports {clk24}]

#Derive PLL Clocks
derive_pll_clocks -gen_basic_clock

#Set False Path
set_false_path  -through [get_nets {kernel/reset/key_down}]
set_false_path  -through [get_nets {kernel/reset/pwr_event}]

